const CONSTANTS = {
  SIGNUP: 'SIGNUP',
  RESETTING_PASSWORD_ACTION: 'RESET_PASSWORD_ACTION',
  RESETTING_ERROR_ACTION: 'RESETTING_ERROR_ACTION',
  RESET_PASSWORD_ACTION: 'RESET_PASSWORD_ACTION',
  ERROR_ACTION: 'ERROR_ACTION',
  LOGIN: 'LOGIN',
  SOCIALLOGIN: 'SOCIALLOGIN',
};

export default CONSTANTS;
