const CONSTANTS = {
  SIGNUP: 'SIGNUP',
  RESETTING_PASSWORD_ACTION: 'RESET_PASSWORD_ACTION',
  RESETTING_ERROR_ACTION: 'RESETTING_ERROR_ACTION',
  RESET_PASSWORD_ACTION: 'RESET_PASSWORD_ACTION',
  ERROR_ACTION: 'ERROR_ACTION',
  LOGIN: 'LOGIN',
  SOCIALLOGIN: 'SOCIALLOGIN',
  POST_ARTICLE: 'POST_ARTICLE',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  FETCH_ARTICLE: 'FETCH_ARTICLE',
  FETCH_ALL_ARTICLES: 'FETCH_ALL_ARTICLES',
};

export default CONSTANTS;
