const CONSTANTS = {
  SIGNUP: 'SIGNUP',
  RESETTING_PASSWORD_ACTION: 'RESET_PASSWORD_ACTION',
  RESETTING_ERROR_ACTION: 'RESETTING_ERROR_ACTION',
  RESET_PASSWORD_ACTION: 'RESET_PASSWORD_ACTION',
  ERROR_ACTION: 'ERROR_ACTION',
  LOGIN: 'LOGIN',
  SOCIALLOGIN: 'SOCIALLOGIN',
  POST_ARTICLE: 'POST_ARTICLE',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  FETCH_ARTICLE: 'FETCH_ARTICLE',
  FETCH_ALL_ARTICLES: 'FETCH_ALL_ARTICLES',
  RATE_ARTICLE: 'RATE_ARTICLE',
  AVERAGE_RATING: 'AVERAGE_RATING',
  RATING_ERROR: 'RATING_ERROR',
  VERIFY: 'VERIFY',
  LOAD_PROFILE: 'LOAD_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  LOAD_USER_ARTICLES: 'LOAD_USER_ARTICLES',
  LOAD_FAVE_ARTICLES: 'LOAD_FAVE_ARTICLES',
};

export default CONSTANTS;
